version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sakila_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sakila
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d  # Ejecuta los scripts .sql al iniciar
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: